library(dplyr)
setwd("~/gse162500/expr_mean")
cd38<-read.table("cd38",header=TRUE)
expr_groups_cd38<-group_by(cd38,Identity)
mean_cd38<-summarise(expr_groups_cd38,expr_mean=mean(Expression))
write.csv(mean_cd38,"mean_cd38.csv")

cd69<-read.table("cd69",header=TRUE)
expr_groups_cd69<-group_by(cd69,Identity)
mean_cd69<-summarise(expr_groups_cd69,expr_mean=mean(Expression))
write.csv(mean_cd69,"mean_cd69.csv")

cd8a<-read.table("cd8a",header=TRUE)
expr_groups_cd8a<-group_by(cd8a,Identity)
mean_cd8a<-summarise(expr_groups_cd8a,expr_mean=mean(Expression))
write.csv(mean_cd8a,"mean_cd8a.csv")

cd8b<-read.table("cd8b",header=TRUE)
expr_groups_cd8b<-group_by(cd8b,Identity)
mean_cd8b<-summarise(expr_groups_cd8b,expr_mean=mean(Expression))
write.csv(mean_cd8b,"mean_cd8b.csv")

entpd1<-read.table("entpd1",header=TRUE)
expr_groups_entpd1<-group_by(entpd1,Identity)
mean_entpd1<-summarise(expr_groups_entpd1,expr_mean=mean(Expression))
write.csv(mean_entpd1,"mean_entpd1.csv")

gzma<-read.table("gzma",header=TRUE)
expr_groups_gzma<-group_by(gzma,Identity)
mean_gzma<-summarise(expr_groups_gzma,expr_mean=mean(Expression))
write.csv(mean_gzma,"mean_gzma.csv")

gzmh<-read.table("gzmh",header=TRUE)
expr_groups_gzmh<-group_by(gzmh,Identity)
mean_gzmh<-summarise(expr_groups_gzmh,expr_mean=mean(Expression))
write.csv(mean_gzmh,"mean_gzmh.csv")

myo1f<-read.table("myo1f",header=TRUE)
expr_groups_myo1f<-group_by(myo1f,Identity)
mean_myo1f<-summarise(expr_groups_myo1f,expr_mean=mean(Expression))
write.csv(mean_myo1f,"mean_myo1f.csv")

syne1<-read.table("syne1",header=TRUE)
expr_groups_syne1<-group_by(syne1,Identity)
mean_syne1<-summarise(expr_groups_syne1,expr_mean=mean(Expression))
write.csv(mean_syne1,"mean_syne1.csv")

tsc22d3<-read.table("tsc22d3",header=TRUE)
expr_groups_tsc22d3<-group_by(tsc22d3,Identity)
mean_tsc22d3<-summarise(expr_groups_tsc22d3,expr_mean=mean(Expression))
write.csv(mean_tsc22d3,"mean_tsc22d3.csv")

xcl2<-read.table("xcl2",header=TRUE)
expr_groups_xcl2<-group_by(xcl2,Identity)
mean_xcl2<-summarise(expr_groups_xcl2,expr_mean=mean(Expression))
write.csv(mean_xcl2,"mean_xcl2.csv")